### ISSUE TITLE
Allow to pass java options to launch script

### ISSUE THREAD

**Issue by akulshin** [xerial/sbt-pack#106]
Hi! just add following code to your launch.mustache template 

``` bash
addJava () {
  dlog "[addJava] arg = '$1'"
  JAVA_OPTS=( "${JAVA_OPTS[@]}" "$1" )
}

process_args () {
  while [[ $# -gt 0 ]]; do
    case "$1" in
            -D*) addJava "$1" && shift ;;
    esac
  done

}

process_args "$@"
```

This will allow to pass additional options, in my case this let me able to point custom config flle to my application.

**Comment by akulshin** [comment]
The code above works with bash and for linux you would need to change the first line to 

```bash
#!/bin/bash
```

**Comment by morgen-peschke** [comment]
This would be really useful for projects which use libraries, like TypeSafe's Config, which allow behavior overrides using system properties.

**Comment by xerial** [comment]
Sorry for the delay of the response. Looks a good idea. Could you create a PR for this?

**Comment by akulshin** [comment]
Seems I have not enough rights to create a branch...

**Comment by morgen-peschke** [comment]
@akulshin I think you need to fork the project and create the PR from a branch on your fork.

**Comment by xerial** [comment]
Done in #118
