### ISSUE TITLE
Option to exclude scala version from packJarNameConvention

### ISSUE THREAD

**Issue by rockwotj** [xerial/sbt-pack#112]
Right now jars come out as `${name}_${scalaVersion}-${version}.jar` is there anyway to just have it be `${name}-${version}.jar` or can you add the ability to manually specify it?

Right now I have a hack to rename the files after the plugin runs, but it'd be nice not to have to do this.

**Comment by xerial** [comment]
It may be possible by adding a new convention type here:
https://github.com/xerial/sbt-pack/blob/f09640367e160dc2ddf9206517ff4bd7f2ad1846/src/main/scala/xerial/sbt/Pack.scala#L216

Just from curiosity, why do you need to remove scalaVersion?

**Comment by rockwotj** [comment]
Moving a project to SBT from maven and all of the deployment and management needs this naming scheme. Not impossible to change, but makes the migration much easier.

**Comment by rockwotj** [comment]
BTW, this plugin pretty great, thanks for building it!
