### ISSUE TITLE
Simple fixes to the Readme file

### ISSUE THREAD

**Issue by jpramondon** [xerial/sbt-pack#115]
This really is some great work happening in here.
Using your plugin I packaged an app with the intention to deploy through a Docker container. What's good is that there's actually a Docker section in your Readme file. What's less is that there are 2 typos that could lead people to think it does not work:
- first is the ENTRYPOINT entry: it should definitely read ENTRYPOINT ["sh", "./bin/myapp"], otherwise one could end up with an error message like "standard_init_linux.go:178: exec user process caused "exec format error""
- second is the "-rm" option for the "docker run" command. I think you meant "--rm"

I could do this for you if you like ;)

**Comment by xerial** [comment]
@jpramondon Thanks. I was a bit in a rush to add this section. I'd appreciate if you can create a PR fixing these typos.

**Comment by jpramondon** [comment]
I'm on it then @xerial 
Hope to send a PR today

**Comment by jpramondon** [comment]
Hi @xerial
Repo cloned, fixed the Readme in a local 'feature/readmeDocker' branch, but can't seem to be allowed to push it to start a PR.

**Comment by xerial** [comment]
@jpramondon FYI. Creating a simple PR for such a fix is quite easy:

![image](https://user-images.githubusercontent.com/57538/29245139-dfbd3dc4-7f84-11e7-9a4c-72127659a379.png)

Just click edit button and follow the instruction.

**Comment by jpramondon** [comment]
We here have a different process using Github Entreprise. I didn't know it could be that much simple :smile: 
Anyway, PR #116 created.

**Comment by xerial** [comment]
Fixed in #116.
