### ISSUE TITLE
sbt pack is great!  Could the java args change be released?

### ISSUE THREAD

**Issue by patsplat** [xerial/sbt-pack#123]
Am using morgen-peschke's [fork](http://search.maven.org/#artifactdetails%7Ccom.github.morgen-peschke%7Csbt-pack%7C0.9.1-EX2%7Cjar) to pass config options inside a docker container i.e.

`$ ./target/pack/bin/server -Dserver.port=8001`

Looks like the changes already merged in: https://github.com/xerial/sbt-pack/pull/118

Are these changes ready?  How might this be finished up for a 0.9.2 release?

**Comment by xerial** [comment]
Sorry for keep you waiting. Just released sbt-pack 0.9.2
