### ISSUE TITLE
Multi-project builds now include jars from all projects

### ISSUE THREAD

**Issue by eltimn** [xerial/sbt-pack#130]
I have a multi-project build and since v.0.9.0, `pack` is now including jars from all projects, instead of just the current project jar. This includes root, which is just an aggregation project.

I tried using `packExcludeJars`, but that doesn't seem to help.

Thanks. Let me know if you need more details.

**Comment by xerial** [comment]
I think this is a long-standing issue #67. sbt-pack tries to include aggregated projects, not only dependent ones. 

We need to address this somewhere.

**Comment by eltimn** [comment]
I hadn't noticed if my aggregated root jar was included before, but in v0.9.0 it's also including unrelated modules that are not aggregations as well. This worked fine for me with 0.8.2.

I have the following projects in my build; root, core, web, jobs

root is an aggregation of them all.

web and jobs both depend on core and I package them as separate jars as they run on different servers. The problem is that jobs is now being included with web and web with jobs, which causes problems with my app.

**Comment by xerial** [comment]
Related to #67

**Comment by xerial** [comment]
Just released a new version sbt-pack 0.10.0 that probably fixes this issue.

**Comment by xerial** [comment]
Let me merge this issue into #67

**Comment by eltimn** [comment]
Thanks for the update. I just tested this and it works as expected now if I run `pack` from within the sub-project (jobs and web from above).

However, if I run `pack` from the root project it does not work correctly; the dependent jars are not included, nor is the project's own jar, but the root jar is. Also, `pack` runs on root and core even though I only have the plugin enabled on the 2 sub-projects.

I hadn't tried running `pack` in a sub-project directly with ver 0.9.3, I always run it from root. I just tried that and it works correctly that way, too.

I can create a test for you if that helps.

**Comment by xerial** [comment]
So a major change in 0.10.0 is, unless you specify dependsOn(subproject,...), it will not gather dependency from sub projects. I can help you if you can share an example.

Here is an example I created:
https://github.com/xerial/sbt-pack/blob/c6877ed678dfdfb43170160fb9582b06982d0a58/src/sbt-test/sbt-pack/archive-modules/build.sbt#L18-L19

**Comment by xerial** [comment]
@eltimn And also try adding enablePlugins(PackPlugin) to your root project: 
https://github.com/xerial/sbt-pack/blob/c6877ed678dfdfb43170160fb9582b06982d0a58/src/sbt-test/sbt-pack/archive-modules/build.sbt#L15

If you still see the problem, please open another issue ticket so that we can track the problem at ease.
