### ISSUE TITLE
Pack on root project doesn't works properly

### ISSUE THREAD

**Issue by tolikr** [xerial/sbt-pack#132]
I use pack plugin 0.10.0.
Here is example of my project structures:
[testPack.zip](https://github.com/xerial/sbt-pack/files/1621610/testPack.zip)

In real i have few projects in libs directory and few modules that uses some of libs by dependsOn. 
In this example:
If i run 
`sbt 'project module1' pack`
project lib1 was successfully packed and moved to pack directory of module1. That is good.

But if i run 
`sbt pack`
project lib1 wasn't moved to pack directory of module1. That is a problem.

In version 0.8.2
`sbt pack`
did it properly.

**Comment by xerial** [comment]
Since 0.10.0, the root project needs have explicit dependencies (to fix bugs in #67)

So adding dependsOn setting to your build.sbt is necessary to have the same behavior with the previous versions:
```
dependsOn(module1, module2)
```

**Comment by xerial** [comment]
```scala
enablePlugins(PackPlugin)

// This is necessary since sbt-pack 0.10.0
dependsOn(module1, module2) 

lazy val module1 = (project in file("modules/module1")).dependsOn(lib1)
lazy val module2 = (project in file("modules/module2")).dependsOn(lib2)

lazy val lib1 = project in file("libs/lib1")
lazy val lib2 = project in file("libs/lib2")
```

**Comment by xerial** [comment]
If you have a root project (that uses `file(".")) in your build.sbt, add dependsOn to this root project settings.

**Comment by tolikr** [comment]
I added depends on, and now if i ran 
`sbt clean pack`
picture is 
![72fc063721](https://user-images.githubusercontent.com/1284004/34860511-14447618-f76f-11e7-950b-070f86524447.png)
Module2 doesn't have depends on lib1, but lib1 packed to module2 directory.  That is not what i want.

**Comment by xerial** [comment]
That's really weird. Let me check.

**Comment by xerial** [comment]
@tolikr Fixed this issue in 0.10.1. I'll release this version soon.

**Comment by xerial** [comment]
@tolikr 0.10.1 is out, and actually I added your test project as a test case, https://github.com/xerial/sbt-pack/tree/master/src/sbt-test/sbt-pack/nested-project

Hopefully this version fixes your problem.

**Comment by tolikr** [comment]
Thanks, it works as expected now.
