### ISSUE TITLE
I cannot build sbt-pack locally

### ISSUE THREAD

**Issue by liebichw** [xerial/sbt-pack#143]
I upgraded my local repository to the current master branch of this repository.
Now when starting sbt to build the plugin, I get errors:
`sbt-pack/build.sbt:47: error: not found: value ReleaseStep`
`sbt-pack/build.sbt:48: error: not found: value action`

**Comment by liebichw** [comment]
Update: I can build the version tagged with v0.11. This version can be compiled by me.

**Comment by liebichw** [comment]
No longer relevant

**Comment by xerial** [comment]
Release plugin is no longer used in the current build.sbt. Probably your local workspace is not up to date
