### ISSUE TITLE
Launch script can load system properties but not java options

### ISSUE THREAD

**Issue by aiyanbo** [xerial/sbt-pack#151]
```
bin/server -Da=b -javaagent=abc.jar
```
the `-D` argument will be insert before to `MAIN_CLASS` but not `-javaagent`

Launch script can support `-J` argument like [sbt-native-packager](https://github.com/sbt/sbt-native-packager)

**Comment by hokor** [comment]
`JAVA_OPTS="-javaagent=abc.jar" bin/server -Da=b`
