### ISSUE TITLE
pack not recognized

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [xerial/sbt-pack#165]
Migrated from sbt-pack 0.10.2 to 0.12 and the result is that it doesn't recognize this line:

    mysubproject / Compile / pack

Error message:

    References to undefined settings:

Using SBT 1.3.0, Java 8, Linux 64 bits.

**Comment by xerial** [comment]
You need to add enablePlugin(PackPlugin) to your sub project settings.

**Comment by DavidPerezIngeniero** [comment]
That's the solution.  Thanks.
