### ISSUE TITLE
packArchiveZip discards execute permission

### ISSUE THREAD

**Issue by matthiasS-da** [xerial/sbt-pack#189]
When creating an archive with `packArchiveZip` and then unpacking it, executable files no longer have execute permissions. 

Inspecting the file with `unzip -Z` reveals:
```
-rw----     2.0 fat     4203 bl defN 19-Dec-20 18:07 myExecutableFile
```
So it seems that the file system / permissions are set incorrectly in the zip file.

I am doing this on Mac OS Mojave, with sbtPack v0.12, unzip 6.00 by Info-Zip.

Please try to fix or let me know if this is a problem of unzip.

**Comment by xerial** [comment]
sbt-pack might not be propagating the file permission properly to the zip file entry:
https://github.com/xerial/sbt-pack/blob/master/src/main/scala/xerial/sbt/pack/PackArchive.scala#L80

We may need to call setUnixMode as well: https://commons.apache.org/proper/commons-compress/apidocs/org/apache/commons/compress/archivers/zip/ZipArchiveEntry.html#setUnixMode-int-

**Comment by matthiasS-da** [comment]
Any plans to fix this? If not, we need to think about a workaround downstream.

**Comment by xerial** [comment]
@matthiasS-da I'd like to fix this issue. Having a pull request for this issue will help me a lot as adding such a fix will take several hours or half-day. 

Currently, sbt-pack only ensures setting permissions at files inside `bin` folder:
https://github.com/xerial/sbt-pack/blob/master/src/main/scala/xerial/sbt/pack/PackArchive.scala#L57

**Comment by matthiasS-da** [comment]
Thanks for clarifying.
