### ISSUE TITLE
New release of sbt-pack?

### ISSUE THREAD

**Issue by smarter** [xerial/sbt-pack#214]
There's been at least one bug fixed in master since the last release: https://github.com/xerial/sbt-pack/commit/128cd434084e13f31349898b1f7201ff33fe29fb, it would be nice to have a release of sbt-pack with this commit in as we're hitting this bug in dotty: https://github.com/lampepfl/dotty/issues/8703

**Comment by xerial** [comment]
I've forgotten to release sbt-pack 0.13. Just published a new version. Thanks for checking.
