### ISSUE TITLE
packAutoSettings missing

### ISSUE THREAD

**Issue by danielnorberg** [xerial/sbt-pack#216]
Seems packAutoSettings is gone. Should mention of it be removed from the readme?

**Comment by aieeeeeee** [comment]
I have the same problem

**Comment by xerial** [comment]
@danielnorberg Hi. I just noticed this ticket. Nice to see you again. Yeah. It should be removed from the doc.

**Comment by xerial** [comment]
Fixed

**Comment by danielnorberg** [comment]
Thanks! 🙌

**Comment by danielnorberg** [comment]
And nice to see you again too! 🙂
