### ISSUE TITLE
Allow for packArchiveStem to be null

### ISSUE THREAD

**Issue by SamStephens** [xerial/sbt-pack#237]
The PackArchive class expects to always put the packaged files in an initial subdirectory. So you end up with a directory structure similar to:

${packArchiveStem.value}/bin
${packArchiveStem.value}/lib
${packArchiveStem.value}/Makefile
${packArchiveStem.value}/VERSION

If it were possible to set packArchiveStem to null (or something similar), and have the package files and folder put into the root of the archive, packArchive would be a perfect tool for building a ZIP file for use with AWS Lambda. AWS Lambda will not look into a subdirectory, it expects that the lib folder will be in the root directory of the archive.

**Comment by xerial** [comment]
It should be possible to support this use case by changing some code assuming the stem folder is not null. I'm ok with adding such a feature, but no time to working on it soon. I'd be happy to review a PR and release a new version.

**Comment by xerial** [comment]
An empty string "" can be used for packArchiveStem. 0.14 with this support will be released soon.
