### ISSUE TITLE
JVM_OPT is a confusing env var name (as opposed to JAVA_OPTS)

### ISSUE THREAD

**Issue by eallik** [xerial/sbt-pack#36]
I do not see why https://github.com/xerial/sbt-pack/pull/5 used the envvar name `JVM_OPT` is `JAVA_OPTS` is already the one used by Java itself.

I think it would make sense to use `JAVA_OPTS` instead. For example I just wasted 30 minutes trying to understand why my code isn't picking up the parameters passed into it.

**Comment by yuranos** [comment]
Is it documented somewhere what the difference between `JVM_OPT` and `JVM_OPTS` is? I was also trying to pass debugging config to `JVM_OPT` and spend quite some time figuring out why it doesn't work.
