### ISSUE TITLE
Ordering of jar inclusion (class path) in launch scripts

### ISSUE THREAD

**Issue by pierre-borckmans** [xerial/sbt-pack#40]
The scripts generated in the ``target/pack/bin``folder by default include every files in the ``target/pack/lib``folder.   
It turns out in some situations, the order of inclusion on the class path matters.

I have already faced two situations of this kind:

1. When using log4j, if any of the jars in the lib folder contain a ``log4j.properties``file, the file I am shipping in my project gets overriden by this file if my jar is not loaded before. 

2. Trying to build a Spark (spark.apache.org) application, I have a simple example where using ``sbt run``works perfectly, but using the launch script generated by ``sbt pack``fails. The only culprit I could find is the order of inclusion on the class path.

Wouldn't it be useful to try to preserve the sbt order of inclusion for the class path ? (I have no idea how to achieve this though).
This order can be inspected with the command: ``show runtime:fullClasspath``

**Comment by xerial** [comment]
Let me close this ticket.
