### ISSUE TITLE
Make packResourceDir a Map[File, String]

### ISSUE THREAD

**Issue by choffmeister** [xerial/sbt-pack#43]
I would find it very useful, to make packResourceDir a `Map[File, String]` instead of a `Seq[String]`. The default value would be

``` scala
packResourceDir := Map(baseDirectory / "src/pack" -> "")
```

meaning that the directory `src/pack` is copied to `target/pack` directory. Adding

``` scala
packResourceDir += Map(target / "web" -> "web")
```

would than mean: "In addition copy the content from `target/web` to `target/pack/web`."

I need this to incorporate [sbt-web](https://github.com/sbt/sbt-web) into my sbt-pack process. By now I have to manually copy the generated web content from sbt-web via `IO.copyDirectory` to get the wanted folder structure.

**Comment by eugeny-stoyka** [comment]
Map is bad if you want specific order to copy resources, for example i want to copy pack directory into another folder (my case is rare but map copy not in seq order)
