### ISSUE TITLE
junit included

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [xerial/sbt-pack#59]
I have a multi-module project.

If I execute:

    sbt mymodule/pack

then `junit-3.7.jar` is also placed in `mymodule/target/pack/lib`, even though it doesn't appear when in the dependency graph done the [sbt-dependency-graph plugin](https://github.com/jrudolph/sbt-dependency-graph).

Is this a bug?

**Comment by xerial** [comment]
Could show me your project files? sbt-pack doesn't use junit-3.7, so I have no clue what is happening.

**Comment by xerial** [comment]
sbt-pack does not use junit, so junit might be included from some project dependency:
```
> dependency-tree
[info] org.xerial.sbt:sbt-pack:0.7.1-SNAPSHOT
[info]   +-org.apache.commons:commons-compress:1.9
[info]   +-org.fusesource.scalate:scalate-core_2.10:1.6.1
[info]   | +-org.fusesource.scalate:scalate-util_2.10:1.6.1 [S]
[info]   | | +-org.slf4j:slf4j-api:1.6.1
[info]   | |
[info]   | +-org.scala-lang:scala-compiler:2.10.5 [S]
[info]   | | +-org.scala-lang:scala-reflect:2.10.5 [S]
[info]   | |
[info]   | +-org.slf4j:slf4j-api:1.6.1
[info]   |
[info]   +-org.tukaani:xz:1.5
```
