### ISSUE TITLE
sbt-pack should not pack dependencies in aggregation modules.

### ISSUE THREAD

**Issue by clockfly** [xerial/sbt-pack#67]
```
  lazy val root = Project(
    id = "root",
    base = file("."),
    settings = commonSettings ++
      packSettings
  ).dependsOn(module1)
   .aggregate(module1, module2)
```

Dependencies jars in module2 should not be copied to generated package.

**Comment by clockfly** [comment]
I saw some one reported this one year ago, is this issue still target to be fixed in 0.6.x?
https://github.com/xerial/sbt-pack/issues/31

**Comment by tolikr** [comment]
Is this fixed? In 0.9.0 issue is still exists.

**Comment by xerial** [comment]
Not yet. This will change the behavior of sbt-pack, so it will be 0.10.x or so

**Comment by tolikr** [comment]
I have a project with such structures:
val x = (project in file('x')) depends on xz
val z = (project in file('z')) depends on xz
val xz project in file('xz')
If i use pack version 0.8.2: 
I have in all projects x,y,xz in pack directory right dependencies.
But after 0.8.2, in 0.9.1 for example. Picture has changed:
in x/target/pack i have z project. It shouldn't be there. I tried to fix this by turn off aggregation in root project but this breaks all packs. 

So i have to use 0.8.2.

**Comment by allanrenucci** [comment]
We are currently using `sbt-pack` in Dotty and this issue prevents us from upgrading to sbt1

**Comment by xerial** [comment]
@allanrenucci That's bad. I'll check how to avoid this issue in sbt-pack side.

**Comment by xerial** [comment]
@clockfly @allanrenucci Just created a new version sbt-pack 0.10.0, which probably fixes this issue. From this version sbt-pack only includes dependent modules specified by `dependsOn`.

**Comment by xerial** [comment]
Let me close this issue now that 0.10.0 is on Maven central. If you still have this issue, let me know.
