### ISSUE TITLE
wrong path format when packing on windows

### ISSUE THREAD

**Issue by clockfly** [xerial/sbt-pack#68]
When trying tar.gz or zip on windows, it will use the backslash "\" for packing, this is not compatible with Linux, linux wiill not be able to decompress it.

When unpacking, it will treat "folder\filename" as a file name.

The better way is to always use slash "/" for packing.

**Comment by xerial** [comment]
@mkroli 
Do you have any idea on fixing this?

**Comment by mkroli** [comment]
@xerial, @clockfly please have a look at #69

**Comment by xerial** [comment]
@mkroli 
Thanks for the fix!

**Comment by xerial** [comment]
Fix is available in sbt-pack 0.6.9

**Comment by clockfly** [comment]
Thanks!
