### ISSUE TITLE
Scala version in the tarball's ArtifactID

### ISSUE THREAD

**Issue by sebastiaansamyn-tc** [xerial/sbt-pack#74]
It often does not make much sense to have the scala version in the artifact name of an application tarball. In our case, trouble with our automated deploys made me wonder what the added value is of having the scala version in the artifactId (for a tarball, I do undestand the point for jars). 

Would it be difficult to introduce a config parameter that makes this optional?

**Comment by xerial** [comment]
How about setting `crossPaths := false`?

**Comment by sebastiaansamyn-tc** [comment]
Isn't that a setting for the entire project? I still want my jars to be versioned, because they could be used as libraries, just not the application that's packaged as a tarball by sbt-pack.

**Comment by xerial** [comment]
I got the point. OK. I'll make it configurable using a variable.

**Comment by sebastiaansamyn-tc** [comment]
That'd be awesome, thanks!

**Comment by sebastiaansamyn-tc** [comment]
Any progress on this? 

If you can give me a hint on how to implement it, I could try it myself and create a PR...

Thanks,
Bas.

**Comment by xerial** [comment]
Sorry. I've been occupied in other work.

This part should be configurable as SettingKey:
https://github.com/xerial/sbt-pack/blob/develop/src/main/scala/xerial/sbt/PackArchive.scala#L34-L35

**Comment by sebastiaansamyn-tc** [comment]
Thanks, we'll give it a try in the coming 2 weeks!

**Comment by xerial** [comment]
Use `packArchiveName` to set arbitrary file name to archive files. This feature is available in sbt-pack-0.7.1

**Comment by sebastiaansamyn-tc** [comment]
Dude... you're awesome!
