### ISSUE TITLE
A setting key to define the root directory of pack's output would be helpful

### ISSUE THREAD

**Issue by liebichw** [xerial/sbt-pack#75]
I am managing a project with multiple "site" definitions per customer. Each site contains (site specific) resources, which should be included into the package generated by pack.
Because pack has a fixed output directory, it is rather clumsy to create a "full setup" for all sites.
If it were possible to define the output root directory of "pack" by overriding a setting (say "packOutputRootDirectory" or something similar), it would greatly simplify our build process.

**Comment by liebichw** [comment]
OK, I discovered that by changing packDir, I can at least define own sub directories - this solves 95% of this issue.
Still, if I could set packDir to *arbitrary* values also outside of "target/", it would be great - if this cannot be done, oh well...

**Comment by xerial** [comment]
This line needs to be fixed:
https://github.com/xerial/sbt-pack/blob/develop/src/main/scala/xerial/sbt/Pack.scala#L142

**Comment by liebichw** [comment]
Hi,

Thank you for the fix, it helped me to speed up our delivery process by about a factor of 2.
Only nitpick: At least on linux, if you specify an ABSOLUTE path as the packDir, it gets appended to "target" (i.e.
specifying the packDir as "/home/user/output" results in "/home/user/project/target/home/user/output" as output directory).
But specifying relative paths works as wanted, so it's enough for me..

(sorry for the late answer, had been busy...).

- Wolfgang Liebich

**Comment by liebichw** [comment]
Hi,

Sorry - only now I found in the relnotes the mentioning of "packTargetDir" - this allows absolute paths :-)
