### ISSUE TITLE
packExcludeJars not excluding

### ISSUE THREAD

**Issue by ipostanogov** [xerial/sbt-pack#77]
Here is unexpected `/target/pack/lib/scala-library-2.10.4.jar`

build.sbt
```
packAutoSettings

name := "sbt-pack-exclude-jars"

version := "1.0"

scalaVersion := "2.10.4"

packExcludeJars := Seq("scala-library-.*\\.jar")
```
project/plugins.sbt
```
logLevel := Level.Warn

addSbtPlugin("org.xerial.sbt" % "sbt-pack" % "0.7.3")
```

project/build.properties
```
sbt.version = 0.13.7
```

**Comment by xerial** [comment]
If you want to exclude scala library, use `autoScalaLibrary := false` instead.

**Comment by ipostanogov** [comment]
Doesn't work either.

build.sbt
```
packAutoSettings

name := "sbt-pack-exclude-jars"

version := "1.0"

scalaVersion := "2.10.4"

libraryDependencies += "org.apache.spark" %% "spark-core" % "1.4.0"

packExcludeJars := Seq("scala-library-.*\\.jar")

autoScalaLibrary := false
```

**Comment by xerial** [comment]
I think packExcludeJars doesn't support wild card. If you really want to remove Scala library from the transitive dependency, set the exclusion rule as follows:
```
libraryDependencies += "org.apache.spark" %% "spark-core" % "1.4.0" excludeAll(
  ExclusionRule("org.scala-lang", "scala-library") 
)
```
http://www.scala-sbt.org/0.13/docs/Library-Management.html#Exclude+Transitive+Dependencies

**Comment by ipostanogov** [comment]
The most interesting to me is that `packExcludeJars := Seq("scala-library.*\\.jar")` works.

**Comment by xerial** [comment]
ok. Let me check why wildcard doesn't work.

**Comment by xerial** [comment]
Released sbt-pack-0.7.4 with this fix.

**Comment by ipostanogov** [comment]
```
packAutoSettings

name := "sbt-pack-exclude-jars"

version := "1.0"

scalaVersion := "2.10.5"

libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % "1.4.0" % "provided",
  "com.typesafe.play" %% "play-json" % "2.3.9"
)

packExcludeJars := Seq("scala-reflect-.*\\.jar")

```

**Comment by xerial** [comment]
@ipostanogov 
Does it still fail to exclude some jar?

**Comment by ipostanogov** [comment]
Using `build.sbt` I've provided you'll see `scala-reflect-2.10.4.jar` in `lib`.

**Comment by xerial** [comment]
Thanks. I can reproduce this issue. 
But not sure why these jars are included.

**Comment by xerial** [comment]
I found the cause. The scala-reflect.jar is the original jar file name. So you need to remove `-` from the pattern:
```
packExcludeJars := Seq("scala-reflect.*\\.jar")
```

sbt-pack renames jar files with (artifact)-(version).jar format.

**Comment by ipostanogov** [comment]
Do you know why first one is not working and the second one works?
```
packAutoSettings
scalaVersion := "2.10.4"
crossPaths := false

libraryDependencies ++= Seq(
  "org.scala-lang" % "scala-reflect" % scalaVersion.value
)

packExcludeJars := Seq("scala-library-.*\\.jar", "scala-reflect-.*\\.jar")
```
```
packAutoSettings
scalaVersion := "2.10.5"
crossPaths := false

libraryDependencies ++= Seq(
  "org.scala-lang" % "scala-reflect" % scalaVersion.value
)

packExcludeJars := Seq("scala-library-.*\\.jar", "scala-reflect-.*\\.jar")
```

**Comment by xerial** [comment]
It looks like scala-reflect.jar (not scala-reflect-2.10.4.jar) is downloaded to your ~/.sbt/cache or local folder by spark or play framework.

**Comment by ipostanogov** [comment]
Seems reasonable. Thank you for the clarification and resolving this issue!
