### ISSUE TITLE
Any way to prevent slf4j-nop from being depended upon?

### ISSUE THREAD

**Issue by BardurArantsson** [xerial/sbt-pack#93]
Hi,

I'm in a situation where I want to debug another SBT plugin[1], but the (non-test) dependency on slf4j-nop prevs SLF4J from initializing the correct one (due to the now-classic "multiple-bindings-so-I-won't-log-anything" issue) with no real way to force the correct binding to be chosen. The end result is that I simply cannot debug what the other plugin is doing.

I can think of two solutions:

* Change the slf4j-nop dependency to "test" scope. This works fine, but will lead to serious-sounding warnings if there are *no* logger implementations on the classpath when the user loads the SBT project. This could perhaps be alleviated by documentation and is the more "general" solution in that it doesn't matter what other plugins are using at all.
* Change to slf4j-simple. This seems to be what sbt-less (or its dependency sbt-web) is depending on.

I have a hard time imagining a scenario where one would choose anything other than slf4j-simple for logging in the *build* itself, so I'd like to suggest the latter solution.

(I'll be happy to provide a pull request -- just ask if you want me to.)

What do you think?

**Comment by BardurArantsson** [comment]
Ping?

**Comment by xerial** [comment]
I hardly remember why I should include slf4j-nop into the dependency (I guess some libraries are requiring it). Switching to slf4j-simple is fine and welcome the PR.

Sorry for the delay of my response.
