### ISSUE TITLE
How can I copy all the resource files to a folder like 'config' in same level with 'lib'

### ISSUE THREAD

**Issue by tlarevo** [xerial/sbt-pack#95]
Hi, I want to copy all the resources files i.e config files, to a folder which is in the same hierarchy with the lib and bin and when app starts it should load the config files from this folder. Can I do this by creating Build script or is it not possible without source code edit ?
 
Thanks in advance

**Comment by tlarevo** [comment]
Its possible do this with the Build.scala 

Inside the,
```scala
object Build extends sbt.Build {
lazy val root = Project(
    id = "my-project",
    base = file("."),
    settings = Defaults.coreDefaultSettings
    ++ Seq(
       // This will copy all the contents in "scr/main/recource" in to pack root(where bin and lib is located)
       packResourceDir += (baseDirectory.value / "src/main/resources/" -> ""),
       // I'm not quite sure whether this is essential but since I needed to externalize my configs and keep them editable and loadable without rebuilding the jar
       packExtraClasspath := Map("conf" -> Seq("${PROG_HOME}/conf"))
   )
}
```

**Comment by filipefigcorreia** [comment]
I too need to copy a few resources to the output, and tried this approach, but with no success. I've created a minimal example to try it outside of my project, but couldn't get it to work. Is this now done differently?

**Comment by lespea** [comment]
You could try https://github.com/sbt/sbt-native-packager or https://github.com/sbt/sbt-assembly/  I know sbt-native-packager has `/src/main/universal` for any files you want to copy over (or something like that)

**Comment by filipefigcorreia** [comment]
before trying sbt-pack I was using sbt-assembly, but it apparently only allows to create fat jars, which is not what I want. I haven't tried native packager but from the docs I get the idea that it only allows to create fat jars too.

Anyway, would you say that the example provided by @tlarevo above should work? It would be perfect if it did :-)

**Comment by lespea** [comment]
sbt-native-packager does not in fact create fat jars.  It will create a folder with all your dep libs in it along with a launcher and/or a zip containing the bin/lib folders (and any copied files)
