### ISSUE TITLE
How to move the project main jar to pack root with the pack build?

### ISSUE THREAD

**Issue by tlarevo** [xerial/sbt-pack#96]
I need to have my project jar in pack main along with the bin, lib folders rather than in lib folder with the rest of the jar. It is possible to do this using custom Build file ?

**Comment by xerial** [comment]
It would be possible by copying the project jar to some folder, and add this folder to `packResources` configuration. The content within `src/pack/` will be copied by default, so copying the jar to this folder would work.

**Comment by tlarevo** [comment]
Thanks a lot for the reply. Yes it is quite possible to copy the Project(App) jar using the `packResourceDir` as follows
```scala
packResourceDir += (baseDirectory.value / "target/scala-2.11/app.jar" -> "")
```
however it copies the `class` folder which contains the classes along with it. And since it is not intended again not the kind of solution I was looking for. Therefore what I did was to create new command in `build.sbt` which does the `pack` and then move the `app.jar` to the `pack`  folder root
```scala
import java.nio.file.{Paths, Files}

lazy val build = taskKey[Unit]("Build the project and move the App Jar to Pack root")

build := {
  pack.value
  if (Files.exists(Paths.get("target/pack/lib/app.jar"))) {
    IO.move(new File("target/pack/lib/app.jar"), new File("target/pack/app.jar"))
  }
}
```

I hope this is not a bad practice and won't cause issues in the future
